{% set name = "treegp" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c455b5056a131e46f7e160c3b31ad8471a3fd64abdc73e6fe530c7bdd92ecfad

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - treecorr >=4.0
    - fitsio >=0.9.12
    - scikit-learn >=0.18
    - iminuit

test:
  requires:
    - python {{ python_min }}
  imports:
    - treegp

about:
  home: https://github.com/PFLeget/treegp
  license: BSD-3-Clause
  license_file: LICENCE
  summary: treegp is a python gaussian process code that perform 1D and 2D interpolation.

extra:
  recipe-maintainers:
    - beckermr
