{% set name = "treegp" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ab2c1c097682e56d8fa74293440b6404dad77ee6b4e2f55e2be565539bb9599

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - treecorr >=4.0
    - fitsio >=0.9.12
    - scikit-learn >=0.18
    - iminuit

test:
  imports:
    - treegp

about:
  home: https://github.com/PFLeget/treegp
  license: BSD-3-Clause
  license_file: LICENCE
  summary: treegp is a python gaussian process code that perform 1D and 2D interpolation.

extra:
  recipe-maintainers:
    - beckermr
