{% set name = "treegp" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5afa58ab37e4ddf31aa57a684d5fccc6ef35a66ded607fdd0cc067cbd449bebf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - treecorr >=4.0
    - fitsio >=0.9.12
    - scikit-learn >=0.18
    - iminuit

test:
  requires:
    - python {{ python_min }}
  imports:
    - treegp

about:
  home: https://github.com/PFLeget/treegp
  license: BSD-3-Clause
  license_file: LICENCE
  summary: treegp is a python gaussian process code that perform 1D and 2D interpolation.

extra:
  recipe-maintainers:
    - beckermr
